//-----------------------------------------------------------------------------
// <auto-generated/>
// <summary> 
// Объекты и конструктор класса главного окна.
// </summary> 
//-----------------------------------------------------------------------------
using SWtaskM.WPF.UI.Controls;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;

namespace SWtaskM.WPF.UI
{
    /// <summary>
    /// Логика взаимодействия для MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        MainControl mainControl;
        public MainWindow()
        {
            InitializeComponent();
            mainControl = new MainControl();
        }

        #region События окна
        /// <summary>
        /// Загрузка окна приложения.
        /// </summary>
        private void WindowLoaded(object sender, RoutedEventArgs e)
        {
            gridDirector.Children.Add(mainControl);
        }

        /// <summary>
        /// Перемещение окна.
        /// </summary>
        private void GridMouseLeftButtonDown(object sender,
                                             MouseButtonEventArgs e)
        {
            DragMove();
        }
        #endregion

        #region Обработка нажатий клавиш
        /// <summary>
        /// Обработка кнопки "Выход".
        /// </summary>
        private void ButtonExitClick(object sender, RoutedEventArgs e)
        {
            Application.Current.Shutdown();
        }
        #endregion

        #region События меню
        /// <summary>
        /// Обработка кнопки меню "Домой".
        /// </summary>
        private void ListViewMenuSelectionChanged(object sender,
                                                  SelectionChangedEventArgs e)
        {
            gridDirector.Children.Clear();
            gridDirector.Children.Add(mainControl);
        }
        #endregion
    }
}
